### ISSUE TITLE
EMAXLEN Max header size for a MIME node exceeded options.maxHeadSize 

### ISSUE THREAD

**Issue by iamDonkey** [andris9/mailsplit#13]
Hi again dear andris, @andris9 
i am getting this error `EMAXLEN`  `Max header size for a MIME node exceeded`  thrown at https://github.com/andris9/mailsplit/blob/master/lib/message-splitter.js#L363

i investigated cause of the error and found options.maxHeadSize has a default value of 1MB 
https://github.com/andris9/mailsplit/blob/master/lib/message-splitter.js#L6
https://github.com/andris9/mailsplit/blob/master/lib/message-splitter.js#L21

although the [readme.md](https://github.com/andris9/mailsplit#split-message-stream) says it is infinity by default? :thinking:

**Comment by andris9** [comment]
Docs are not properly updated. The max header value was set as part of mitigations for this [security advisory](https://snyk.io/vuln/npm:mailsplit:20180625).

**Comment by iamDonkey** [comment]
but i am getting this error for some mails does that mean its an attack? and i have not had chance to look into the raw mail content. just saw these error in the console.
in general, do you think any possibility that a genuine mail can have more than 1MB of headers? :thinking: 

if i want to increase the size do i just have to put here?
`let parser = new MailParser({maxHeadSize: 2 * 1024 * 1024});`
