### ISSUE TITLE
Creating MIME tree, modifying content and the outputting to raw email

### ISSUE THREAD

**Issue by amit777** [andris9/mailsplit#17]
Hi, I discovered this module because it's used by mailparser to create a MIME Tree.

Rather than using the streaming interface to modify individual nodes, is it possible to construct the tree of nodes, modify some of the elements, and then output the resulting tree into a standard eml format?

The reason is because we have a use-case that requires modifying some nodes in a tree based on the content of their parent/sibling/children nodes. 

Thank you!

**Comment by andris9** [comment]
This module only allows doing this while streaming. If you want to manage the entire tree, then you could probably use the Splitter interface to split the MIME message into nodes, then build the tree structure yourself out of these nodes, run the modifications and finally use the Joiner interface to turn nodes back into the EML file.

**Comment by amit777** [comment]
Thank you! I noticed that your other awesome `mailparser` module actually creates a tree structure, ie `mailparser.tree`.  I was just actually trying to figure out how to apply the Joiner interface to that `mailparser.tree` structure.  Would this conceptually work?  I'm not very adept with streaming interfaces, so if you have any code examples of taking this tree, and feeding it to the Joiner stream, that would be very appreciated.

In addition, We are interested in sponsoring development of helper functions on these modules that achieve some of the things we are looking for.  If that is something of interest to you, I'll send you an email!  I think they would mainly be function wrappers around your existing code that would provide a non-streaming way of working with the MIME tree.

**Comment by andris9** [comment]
You can use the Mailparser's tree object, but the resulting EML would have many differences compared to the original. For example, Mailparser would normalize all text content, etc. The streaming and joining interfaces of Mailsplit allow you to generate emails that look almost exactly the same as the source. Mailsplit would only touch some specific parts you want to modify and leave everything else as it is. So you could modify emails by changing only a few bytes.

**Comment by amit777** [comment]
Got it.  Would you be open to sponsored development of the mailsplit module.  Specifically the following set of methods:

1. `parseEntity(eml_string)` Parses the eml into a MimeNode tree
2. `bodystring`  accessor method on each MimeNode that let's you get/set the content of the body in the node.
3. `stringifyEntity(mimenode_tree)`  this would take the tree, and output the result like the Joiner interface does.


We are trying to move away from a legacy perl based system that uses MIME::Tools.  Your module comes the closest!

**Comment by andris9** [comment]
I guess I *could* add these features, but the issue is that I have so much other work piled up with my email startup [EmailEngine](https://emailengine.app/) that I don’t have much time for other stuff, so I can’t provide any ETAs 🤷‍♂️

**Comment by amit777** [comment]
Thanks Andris!  I'll email you to see if we can work something out.
