### ISSUE TITLE
[bug] Max header size for a MIME node exceeded

### ISSUE THREAD

**Issue by blephy** [andris9/mailsplit#19]
Hi,

I'm using `mailparser` which use this library. I'm getting a lot of 

```txt
Failed handling notification Error: Max header size for a MIME node exceeded at MessageSplitter.processLine (/node_modules/mailsplit/lib/message-splitter.js:363:31) at Immediate.iterateData (/node_modules/mailsplit/lib/message-splitter.js:79:33)
```

using `SimpleParser` class from `mailparser` without any option.

Do you have any explanation on this ? 
Is the mail headers are too big or the entier mail ?
Do we have a workaround as the `maxHeadSize` option is not override ?

**Comment by andris9** [comment]
`maxHeadSize` is 1MB. Do you really have real-life emails with such large headers? Is there anything special with these emails? Do you know why the headers are so big?

**Comment by blephy** [comment]
IDK i will investigate but this seems to be a normal situation with health data 😄 

maxHeadSize is 1MB or infinite ? the documentation say infinite

How can i know where the header start and stop in a mail ?

**Comment by blephy** [comment]
I cannot give you an EML example, i will try to make an integration testing on my side, and if i can reproduce it, i will erase the sensitive health data from it before exposing you

**Comment by blephy** [comment]
I did some spec.

we are doing like this in production : 

```ts
const emailParsed = await simpleParser(rawEML);

const attachementsParsed = await simpleParser(emailParsed.attachments[0].content.toString());

// failed here.
```

I did try with an EML containing an attachement containing `1141164` bytes => `1.088298798` MiB : failed.

Increasing the `maxHeadSize` did the tricks.
