### ISSUE TITLE
Unicode characters lost due to `toString('binary')`

### ISSUE THREAD

**Issue by titanism** [andris9/mailsplit#21]
Hi there @andris9 

If a header such as `From: Test <xin@日本語.org>` exists, then this library will convert it to `Test <xin@æ¥æ¬èª.org>` due to the following lines: 

https://github.com/andris9/mailsplit/blob/37b0d216d84bae0b2efacd65a3c2d89d8452b323/lib/headers.js#L197-L200

What is the purpose of using `'binary'` as opposed to leaving as just `toString()`?

**Comment by andris9** [comment]
This is intentional. Otherwise headers that use non utf8 like win-1257 will break.

**Comment by andris9** [comment]
Mailsplit parses and _recomposes_ messages. The recomposed message would break if mailsplit would use unicode, not binary strings.
