### ISSUE TITLE
Possible issue with `\t` character (e.g. in `DKIM-Signature` header)

### ISSUE THREAD

**Issue by titanism** [andris9/mailsplit#22]
Hi @andris9  - checking here to see if you think you should modify this line as such?

<https://github.com/andris9/mailsplit/blob/37b0d216d84bae0b2efacd65a3c2d89d8452b323/lib/headers.js#L197-L200>

```diff
        let lines = this.headers
            .toString('binary')
+           .replace(/\r?\n?\t/g, ' ')
            .replace(/[\r\n]+$/, '')
            .split(/\r?\n/);
```

This would support `\t` character that is preceded by a linebreak, such as a `DKIM-Signature` header spanning multiple line breaks with `\t` character.

**Comment by andris9** [comment]
This approach would break mime line folding handling.
