### ISSUE TITLE
Investigating: Possible issue when email contain RFC with header only

### ISSUE THREAD

**Issue by peernohell** [andris9/mailsplit#5]
Hi,

I search an issue in mailparser where, when an email is multi part and have an RFC822 with only header. Mailparser never call the call back when finish.
After some investigation, I think it's may come from mailsplit not calling "end" event.
I will not able to investigate more for today, but if you have any clue or advice on where to look in your greate package, it will help me a lot.
I will provide a test example tomorrow :)

You can take a look to the test code I have write in the issue of mailparser here: https://github.com/nodemailer/mailparser/issues/190

Thanks for your help ❤️

**Comment by peernohell** [comment]
Hi,

After some search. I find that mailsplit.read() didn't call with the node "text/plain" the node under the rfc822 that have only header.

I have create a gist with a test exemple: 
https://gist.github.com/peernohell/b76099d8566702176f7e3e95857cdbfe

here is the result:

```
test end
end!!!!!
readData data[type=node] multipart/mixed
readData is null
readData data[type=data]undefined value="--ABC
"
readData is null
readData data[type=node] message/rfc822
readData is null




*** *** *** *** *** *** *** *** *** *** ***
end!!!!!
readData data[type=node] multipart/mixed
readData is null
readData data[type=data]undefined value="--ABC
"
readData is null
readData data[type=node] message/rfc822
readData is null
readData data[type=node] text/plain
readData is null
```

In the first case, we have an rfc822 with only header.
In the second we have text body inside the rfc822 and we see that in that second case readData is called with a node with contentType text/plain.

I think that in the first case it should also call with a node with the content type text/plain.

If you have any guess or suggestion? Thank ❤️

**Comment by andris9** [comment]
Closing as this does not seem to be relevant anymore
